random_state: 42

model:
  which: 'xgboost'
  dummy: 'prior'
  early_stopping:
    early_stopping_rounds: 10
    eval_metric: [ 'logloss' ]
  bayes_params:
    n_calls: 100
    use_early_stopping: False
    verbose: True
  feature_selection:
    top_k_feats:
      tune: true           # true  → include in BayesOpt space
      low: 5 # 15 # 5
      high: 70 # 35 # 35 # 35. # 70
      fixed_value: 30      # used only if tune == false

    # optional override: bypass top_k_feats selection and use fixed list instead
    fixed_features:
      # ≥ 5/5
      # ['min_peak_prom_iqr', 'asd_4_10th_percentile', 'q25_mag_mean', 'rms_mag_10th_percentile', 'asd_1_skew', 'mean_mag_10th_percentile', 'q25_mag_10th_percentile', 'q25_x_90th_percentile', 'q75_mag_10th_percentile', 'q75_y_10th_percentile', 'med_mag_10th_percentile', 'q25_y_90th_percentile']
      # ≥ 4/5
      # ['asd_1_skew', 'asd_2_10th_percentile', 'asd_4_10th_percentile', 'avg_peak_prom_mean', 'avg_sp_power_10th_percentile', 'max_mag_10th_percentile', 'max_mag_mean', 'max_peak_prom_mean', 'max_y_iqr', 'max_y_mean', 'max_z_mean', 'mean_mag_10th_percentile', 'med_mag_10th_percentile', 'med_mag_mean', 'min_peak_prom_iqr', 'p3_10th_percentile', 'peaks_per_sec_skew', 'q25_mag_10th_percentile', 'q25_mag_mean', 'q25_x_90th_percentile', 'q25_y_90th_percentile', 'q25_y_mean', 'q25_z_90th_percentile', 'q75_mag_10th_percentile', 'q75_x_10th_percentile', 'q75_y_10th_percentile', 'q75_y_mean', 'rms_mag_10th_percentile', 'sp_entropy_mad', 'sp_entropy_std', 'std_y_10th_percentile', 'std_y_mean']
      # ≥ 3/5
      # ['asd_16_10th_percentile', 'asd_1_skew', 'asd_2_10th_percentile', 'asd_4_10th_percentile', 'avg_peak_prom_mean', 'avg_sp_power_10th_percentile', 'loc_first_min_mag_90th_percentile', 'max_mag_10th_percentile', 'max_mag_mean', 'max_peak_prom_mean', 'max_x_mean', 'max_y_iqr', 'max_y_mean', 'max_z_mean', 'mean_mag_10th_percentile', 'mean_mag_mean', 'med_mag_10th_percentile', 'med_mag_mean', 'min_peak_prom_iqr', 'min_peak_prom_mad', 'min_y_90th_percentile', 'min_y_mean', 'min_z_mean', 'p1_10th_percentile', 'p1_skew', 'p3_10th_percentile', 'peaks_per_sec_skew', 'power_10th_percentile', 'q25_mag_10th_percentile', 'q25_mag_mean', 'q25_x_90th_percentile', 'q25_x_mean', 'q25_y_90th_percentile', 'q25_y_mean', 'q25_z_90th_percentile', 'q75_mag_10th_percentile', 'q75_x_10th_percentile', 'q75_y_10th_percentile', 'q75_y_mean', 'rms_mag_10th_percentile', 'sd2_10th_percentile', 'sma_mag_iqr', 'sma_mag_mean', 'sp_entropy_mad', 'sp_entropy_std', 'std_mag_10th_percentile', 'std_y_10th_percentile', 'std_y_mean', 'std_z_mean']

  hp_overrides:


data:
  agg_level: 'night'
  processing:
    scaler:  'robust' # 'robust' # 'minmax', 'standard', 'robust' or 'none'
    scaling_order: 'before_ranking' # 'before_ranking' or 'after_ranking'
    use_smote: True

  loader:
    binary_mapping: {'HC': 0, 'PD-RBD': 0,  'iRBD': 1, 'PD+RBD': 1}
    rebalance_datasets: # for LODO only, to mitigate dataset biases
        method: 'cap_to_second_largest'
        # none: keep original | cap_to_second_largest: cut largest to 2nd largest if ≥ ratio |
        # min: cut all to smallest | equalize_to_median: cut all to median | cap_to_k: cap each at k |
        # proportional_to_quota: downsample to quotas | weights_only: keep all, use weights
        apply_to: 'train'                 # split to affect (train|test); usually "train"
        random_state: 42
        preserve_class_ratio: true        # keep within-dataset RBD/HC mix when downsampling

        # cap_to_second_largest
        dominance_ratio: 1.2             # only cap if largest ≥ ratio × second largest

        # cap_to_k
        k_per_dataset: 100                # hard cap K per dataset (ignored if method != cap_to_k)

        # proportional_to_quota
        quotas: # share per dataset (must sum to 1.0); downsample only
          AAR: 0.25
          CGNtrain: 0.25
          CGNtest: 0.25
          OXF: 0.25


    feature_dir: './features/per_night'  # relative to patient_dir
    aggregation: [ 'mean', 'std', 'skew', 'kurt', 'mad', 'iqr', '10th_percentile', '90th_percentile' ]
    included_local_features: [
      # modes
      'mean_mag', 'std_mag', 'skew_mag', 'kurt_mag',
      'mean_x', 'std_x', 'skew_x', 'kurt_x', 'mean_y', 'std_y', 'skew_y', 'kurt_y', 'mean_z', 'std_z', 'skew_z', 'kurt_z',
      'min_mag', 'q25_mag', 'med_mag', 'q75_mag', 'max_mag',
      'min_x', 'q25_x', 'med_x', 'q75_x', 'max_x',
      'min_y', 'q25_y', 'med_y', 'q75_y', 'max_y',
      'min_z', 'q25_z', 'med_z', 'q75_z', 'max_z',
      # 'iqr_mag', 'iqr_x', 'iqr_y', 'iqr_z',

      # energy
      'sma_mag', 'power', 'rms_mag',

      # spectral
      'asd_1', 'asd_2', 'asd_4', 'asd_8', 'asd_16', 'f1', 'f2', 'f3', 'p1', 'p2', 'p3', 'sp_entropy', 'avg_sp_power',

      # auto-correlation
      'ac_first_max_mag', 'loc_first_max_mag', 'ac_first_min_mag', 'loc_first_min_mag', 'zeros_mag',
      'ac_first_max_x', 'loc_first_max_x', 'ac_first_min_x', 'loc_first_min_x', 'zeros_x',
      'ac_first_max_y', 'loc_first_max_y', 'ac_first_min_y', 'loc_first_min_y', 'zeros_y',
      'ac_first_max_z', 'loc_first_max_z', 'ac_first_min_z', 'loc_first_min_z', 'zeros_z',

      # peaks
      'peaks_per_sec', 'avg_peak_prom', 'max_peak_prom', 'min_peak_prom',

      # non-linear dynamics
      'SampEn_mag', 'hurst_rs_mag', 'SampEn_x', 'hurst_rs_x', 'SampEn_y', 'hurst_rs_y', 'SampEn_z', 'hurst_rs_z',

      # Poincaré
      'sd1', 'sd2', 'sd_ratio', 'ellipse_area'
    ]

    included_global_features: [
      # inter-event-intervals
      'iei_mean_sec', 'iei_std_sec', 'iei_var_sec', 'iei_cv', 'iei_iqr_sec',

      # degree of clustering
      'hopkins_score', 'kde_n_peaks', 'kde_avg_prom', 'kde_max_prom', 'kde_min_prom',

      # overall activity
      'n_moves_per_h',

      # duration modes
      'mean_dur_sec', 'std_dur_sec', 'skew_dur_sec', 'kurt_dur_sec', 'q25_dur_sec', 'med_dur_sec', 'q75_dur_sec',

      # sleep quality proxies
      'sleep_eff', 'waso'
    ]

nested_cv:
  n_repeats:  5
  n_jobs: -1
  stratify_by_dataset_if_pooled: True
  min_patient_nights_eval: 4
  ranking_seed: # defaults to global random_state
  outer_cv:
    n_splits: 5
    shuffle: True
  inner_cv:
    n_splits: 5
    shuffle: True


  n_interp_points_roc_pr:  100
  n_interp_points_calibration: 11
  calib_plot_hist_bin_width: .05
  default_experiment:
    name: 'nested_cv'
    hp_setup_name:
    early_stopping:
    calibration:  'sigmoid' # 'sigmoid'
    threshold:  'default'  # threshold options: default, roc_dist, pr_dist, pr_f1, macro_ba, macro_ba_weighted, roc_dist_per_dataset_mean, roc_dist_per_dataset_median, pr_dist_per_dataset_mean, pr_dist_per_dataset_median, pr_f1_per_dataset_mean, pr_f1_per_dataset_median, fixed:<float>
    patient_aggregation: 'ensemble_major'

  log_night_eval: false
  load_path_cv_feature_rankings:  # leave empty for default



final_model:
    skip_pretrain: True
    n_jobs: -1
    bayes_cv:
      n_splits: 5
      shuffle: True
    bayes_params: { 'n_calls': 100, 'use_early_stopping': False, 'verbose': True }
    stratify_by_dataset_if_pooled: True  # for bayes cv
    # 'early_stopping': {'early_stopping_rounds': 100, 'eval_metric': balanced_accuracy_eval},
    early_stopping: { 'early_stopping_rounds': 10, 'eval_metric': [ 'logloss' ] }
    load_path_feature_rankings: # leave empty for default!
    log_night_level: false
    min_patient_nights_eval: 4
    output_patient_csv: false
    experiments: # define experiment setups to try (note: test set is blinded, so choose one/two setups and only test once)
      - name: 'model1'
        hp_setup_name: 'bayes_opt'
        early_stopping: true
        calibration: 'sigmoid'
        threshold: 'roc_dist'
        patient_aggregation: 'ensemble_major'
      - name: 'model2'
        hp_setup_name: 'bayes_opt'
        early_stopping: true
        calibration: 'sigmoid'
        threshold: 'default'
        patient_aggregation: 'ensemble_major'

    nested_cv_path: # leave empty for default!, otherwise must point to a nested_cv output dir.
    include_pretrain_merged: True # include mode where models are pretrained on concatenated cologne train+test cohort
    save_path_models: # leave empty for default, can be a list for several locations
    calibration_cv:  # cv used for calibrating the model (if specified)
      n_splits: 5
      shuffle: True
    overwrite_final_repo_models: True  # if True, it will also save the models at aktiRBD.models.pretrained

