processing_kwargs:
  resample_rate: 'infer'    # leave empty to skip, use 'infer' for auto
  lowpass_hz: 20            # upper bound of butterworth bandpass (for high frequent, e.g. electronic noise)
  highpass_hz: .8           # lower bound of butterworth bandpass (baseline drift noise)
  skip_calibration: False   # whether to skip gravity calibration or not

feature_kwargs:
  mode: 'per_night'
  filter_move_durations:   # whether to apply the 'toilette' filter to the move episodes before calculating
    # the global features, must be tuple of bound in seconds to activate (independent of data_loader!)
  create_cluster_plots: True
